export const APG_DISPLAY_STATE_META = {
    clarification: {
        key: 'clarification',
        labelHu: 'Tisztázás',
        labelEn: 'Clarification',
        icon: '❓',
        cssClass: 'apg-state-clarification',
        descriptionHu: 'A továbblépéshez pontosítás szükséges.',
        descriptionEn: 'Clarification is needed before work can continue.',
        severity: 'info',
    },
    evidence_needed: {
        key: 'evidence_needed',
        labelHu: 'Bizonyíték szükséges',
        labelEn: 'Evidence needed',
        icon: '🔎',
        cssClass: 'apg-state-evidence-needed',
        descriptionHu: 'A rendelkezésre álló bizonyíték még nem teljes.',
        descriptionEn: 'The available evidence is not yet complete.',
        severity: 'warning',
    },
    executing: {
        key: 'executing',
        labelHu: 'Végrehajtás alatt',
        labelEn: 'Executing',
        icon: '⚙️',
        cssClass: 'apg-state-executing',
        descriptionHu: 'A munka végrehajtása folyamatban van.',
        descriptionEn: 'The work is currently being executed.',
        severity: 'info',
    },
    verifying: {
        key: 'verifying',
        labelHu: 'Ellenőrzés alatt',
        labelEn: 'Verifying',
        icon: '✅',
        cssClass: 'apg-state-verifying',
        descriptionHu: 'Az eredmény és a bizonyítékok ellenőrzése folyamatban van.',
        descriptionEn: 'The result and its evidence are being verified.',
        severity: 'info',
    },
    decision_needed: {
        key: 'decision_needed',
        labelHu: 'Döntésre vár',
        labelEn: 'Decision needed',
        icon: '⚖️',
        cssClass: 'apg-state-decision-needed',
        descriptionHu: 'A továbblépéshez tulajdonosi döntés szükséges.',
        descriptionEn: 'An owner decision is needed before work can continue.',
        severity: 'warning',
    },
    blocked: {
        key: 'blocked',
        labelHu: 'Blokkolt',
        labelEn: 'Blocked',
        icon: '⛔',
        cssClass: 'apg-state-blocked',
        descriptionHu: 'Egy sikertelen kontroll megakadályozza a továbblépést.',
        descriptionEn: 'A failed control prevents further progress.',
        severity: 'danger',
    },
    accepted: {
        key: 'accepted',
        labelHu: 'Elfogadva',
        labelEn: 'Accepted',
        icon: '✓',
        cssClass: 'apg-state-accepted',
        descriptionHu: 'A munka ellenőrzött és elfogadott.',
        descriptionEn: 'The work has been verified and accepted.',
        severity: 'success',
    },
    off: {
        key: 'off',
        labelHu: 'APG kikapcsolva',
        labelEn: 'APG disabled',
        icon: '○',
        cssClass: 'apg-state-off',
        descriptionHu: 'Az APG kontrollréteg ezen a hatókörön ki van kapcsolva.',
        descriptionEn: 'The APG control layer is disabled for this scope.',
        severity: 'muted',
    },
};
